apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster
  namespace: bnctl-dolphinscheduler-prod-ns
  labels:
    app.kubernetes.io/instance: cluster
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cluster